# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'WanAndroidSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.1'
  pod 'RxSwift', '~> 5.0.1'
  pod 'RxCocoa', '~> 5.0.1'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'KakaJSON', '~> 1.1.1'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.9.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.2'
  pod 'KRProgressHUD', '~> 3.4.4'
  pod 'DeviceKit', '~> 2.3.0'
  pod 'SwiftEventBus', '~> 5.0.0'
#  pod 'Permission', '~> 2.0.4' #权限请求
  pod 'SPPermissions', '~> 5.0.9'
  pod 'SkyFloatingLabelTextField', '~> 3.7.0' # 浮动TextField
  pod 'LLCycleScrollView', '~> 1.6.0' #banner
  pod "ESPullToRefresh"
  #PullToRefresh
end
